const html_v1_QR_Top = '<body style="box-sizing: border-box;"><div class="ticket" style=""><div class="ticket-header" style="text-align:center;font-size:30px;">Hi! ' +
receiver.name +
'</div><div class="ticket-body" style="background-color:#ff0012;"><div class="ticket-body__QR" style="margin: auto;width: 200px;padding: 10px;"><img src="https://api.qrserver.com/v1/create-qr-code/?data=' + receiver.submissionId+'&amp;size=100x100" alt="" title="TICKET"width="200" align="middle"/></div><div class="ticket-body__text" style="width:100%;vertical-align:top;text-align:center;font-size:20px;color:white;padding-top:5%;padding-bottom:5%"><div class="ticket-body__text-time" style="">您要观看的演出是(Show Time)：<br/>' +
    receiver.showTime +
    '</div><div class="ticket-body__text-time" style="margin-top:10px;">您注册的票数 (Number of Tickets):&nbsp' +
        receiver.numberOfTix +
        ' </div><div class="ticket-body__text-venue" style="margin-top:10px;">地点(Address):<br/>Dance Atelier 2, Level 3,<br/>Stephen Riady Centre, University Town,<br/>2 College Ave West,<br/>Singapore 138607</div><div class="ticket-body__text-instruction" style="font-size:16px;margin-top:10px;">演出开始前15分钟开始入场<br/>出示上图的二维码作为入场凭据<br/>迟到者可能被拒绝入场<br/>多张票可重复扫描同个二维码</div></div><div class="ticket-body__image" style="margin: auto;width: 300px;padding: 10px;"><img src="https://preview.ibb.co/gET7mS/rhinocero.png" alt="" title="rhino" style="width:100%;"></div></div></div></div></body>'

const html_v2_Rhino_Top =   '<body style="box-sizing: border-box;"><div class="ticket" style=""><div class="ticket-header" style="text-align:center;font-size:30px;">Hi! ' +
receiver.name +
'</div><div class="ticket-body" style="background-color:#ff0012;"><div class="ticket-body__image" style="margin: auto;width: 50%;padding-top:30px;"><img src="https://preview.ibb.co/gET7mS/rhinocero.png" alt="RHINO_PIC" title="rhino" style="width:100%;"></div><div class="ticket-body__text" style="width:100%;vertical-align:top;text-align:center;font-size:20px;color:white;padding-bottom:5%"><div class="ticket-body__text-time" style="">您要观看的演出是(Show Time)：<br/>' +
    receiver.showTime +
    '</div><div class="ticket-body__text-time" style="">您注册的票数 (Number of Tickets):&nbsp' +
        receiver.numberOfTix +
        ' </div><div class="ticket-body__text-venue" style="margin-top:10px;">地点(Address):<br/>Dance Atelier 2, Level 3,<br/>Stephen Riady Centre, University Town,<br/>2 College Ave West,<br/>Singapore 138607</div><div class="ticket-body__text-instruction" style="font-size:16px;margin-top:10px;">演出开始前15分钟开始入场<br/>出示下图的二维码作为入场凭据<br/>迟到者可能被拒绝入场<br/>多张票可重复扫描同个二维码</div></div><div class="ticket-body__QR" style="margin: auto;width: 200px;padding: 10px;"><img src="https://api.qrserver.com/v1/create-qr-code/?data=' + receiver.submissionId+'&amp;size=100x100" alt="QR_CODE" title="TICKET"width="200" align="middle"/></div></div></div></div></body>'